### ISSUE TITLE
core.py의 BaseEnv.derivs 를 rename

### ISSUE THREAD

**Issue by JungYT** [fdcl-nrf/fym#110]
env의 states는 env 내 여러 model들의 state들의 집합이라는 의미에서 s를 붙여 states.
env의 derivs는 env 내 여러 model들의 deriv들의 집합이라는 의미에서 s를 붙여 derivs.
그런데 env의 derivs는 outer loop의 역할도 겸한다.
예를 들어
model의 input이 토크, env의 action이 가속도인 경우 env의 action(가속도)를 받아 model의 input(토크)로 바꿔주는 제어기가 필요하다.
이 과정을 env의 derivs 메소드에서 처리한다. 마치 inner loop, outer loop처럼.
이를 직관적으로 알 수 있도록 메소드를 rename하거나 docstring에 넣어서 활용법을 알려주면 좋을 것 같다.

**Comment by seong-hun** [comment]
Outdated.
