### ISSUE TITLE
다개체 시뮬레이션 시 각 개체별로 done 및 log

### ISSUE THREAD

**Issue by JungYT** [fdcl-nrf/fym#111]
1. 다개체가 돌아가는 env의 경우 그 개체 수를 길이로 하는 done list(혹은 dict등 아무거나)를 만들고,
get_next_states에 done list를 받아서 해당 개체의 done[i]이 True면 아예 적분을 안 하게.(update 안 하게) -> 다개체 시뮬레이션에서 한 개체가 먼저 목적지에 도달하거나 할 경우 그 개체는 더이상 update안 하게
2. 이 경우 log 길이가 달라질 수 있기 때문에 개체별로 log하도록 만들어야 함.

**Comment by seong-hun** [comment]
아마 해결되었을 것 같습니다.
