### ISSUE TITLE
temp log를 on/off 할 수 있도록

### ISSUE THREAD

**Issue by JungYT** [fdcl-nrf/fym#114]
현재 core.py 의 log는 log를 깜빡하고 안 했을 때를 위해 state만 임시로 저장하는 temp log.

다른 여러가지 것들을 저장하고 싶으면 utils의 log class를 사용해서 저장해야한다.

그런데 내가 log class를 사용해서 log를 해도 temp log는 돌아가는 상황.
 
temp log를 on/off 할 수 있으면 좋을듯

* log class를 core.py에 기본으로 넣지 않은 이유 :  매번 저장하고 싶은 것이 달라질 수 있으니까

**Comment by seong-hun** [comment]
이제 가능합니다.
