### ISSUE TITLE
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

### ISSUE THREAD

**Issue by JungYT** [fdcl-nrf/fym#116]
derivs에서 뱉어주는 xdot이 flat 한 ndarray가 아닌 경우 발생하는 것으로 보임

model의 deriv에서 return할 때 np.array([x, y, z]) 이런 식으로 하면 x, y, z의 data type에 따라서 문제가 생김.

이 경우 np.hstack([x, y, z])로 해결함.

위와 같은 error가 나올 경우 이를 검토해보라는 메세지가 나오면 좋을듯

**Comment by seong-hun** [comment]
현재는 모두 2차원 벡터로 처리하게끔 바뀌었습니다.
