### ISSUE TITLE
에러 나면 자동으로 logging이 close하게 할 수 있나요?

### ISSUE THREAD

**Issue by JungYT** [fdcl-nrf/fym#117]
어디선가 에러가 나서 중간에 멈춰버리면 logging이 close 되지 않아서 ipython을 나갔다 와야합니다.

에러가 날 경우 자동으로 logging이 close하도록 만들 수 있나요?

**Comment by seong-hun** [comment]
이거는 짤 때 본인이 그렇게 짜야할 것 같습니다.
