### ISSUE TITLE
길이가 다른 data 저장

### ISSUE THREAD

**Issue by JungYT** [fdcl-nrf/fym#118]
길이가 다른 data를 저장할 수 있나요?

예를들어, 현재는 한 개체가 처음 10초 동안에는 위치 값을 가지다가 어느 시간 이후로는 [] 값을 가질 경우 에러가 납니다.

이런 경우에도 저장할 수 있도록 가능한가요?

**Comment by seong-hun** [comment]
아니오.. 이 기능이 필요할까요?

**Comment by seong-hun** [comment]
필요하면 다시 열어주세요.
