### ISSUE TITLE
config data 저장

### ISSUE THREAD

**Issue by JungYT** [fdcl-nrf/fym#120]
simulation에 사용된 setting 값(spec or config)을 필요하다면 logging된 데이터 저장되는 곳에 같이 저장할 수 있도록 logging class에 method를 만들면 좋을듯.
이때 json 파일로 만드는 것이 여러 곳에서 열어볼 수 있어서 좋다.
np.array를 포함한 데이터를 json 파일로 저장하는 모듈 만들기

**Comment by seong-hun** [comment]
`logger.set_info` 메소드를 사용할 수 있습니다.
