### ISSUE TITLE
Documentation; methods in `fym.utils.rot`

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-nrf/fym#166]
In `fym.utils.rot`, some methods are provided, which are related to rigid body attitude representation.

However, there is no description about "from which to which" coordinate systems, such as inertial coord. to body coord.
I request docstrings for them.

Note: It seems that all unit quaternion, DCM, and Euler angles represent body attitude w.r.t. inertial frame. Also, Euler angles are related to ZYX angles, i.e., yaw, pitch, roll.

**Comment by seong-hun** [comment]
It seems that you need a simple description for what coordinates the DCM transforms.
However, there already exists [a comment](https://github.com/fdcl-nrf/fym/blob/c40448974dd4480ea4135aebb707542145f85c70/fym/utils/rot.py#L7) on that.
Isn't is sufficient?

**Comment by JinraeKim** [comment]
> It seems that you need a simple description for what coordinates the DCM transforms.
> However, there already exists [a comment](https://github.com/fdcl-nrf/fym/blob/c40448974dd4480ea4135aebb707542145f85c70/fym/utils/rot.py#L7) on that.
> Isn't is sufficient?

It's not sufficient.
1. One may be confused with if """DCM: C_{b/i}"""  represents "from b to i" or "i to b". It is merely a conventional representation.
2. No description of the order of Euler angles, e.g., ZYX (first Z applied), XYX, XYZ, etc.
3. No description of the unit quaternion.

**Comment by seong-hun** [comment]
> * No description of the order of Euler angles, e.g., ZYX (first Z applied), XYX, XYZ, etc.

[It exists.](https://github.com/fdcl-nrf/fym/blob/c40448974dd4480ea4135aebb707542145f85c70/fym/utils/rot.py#L63)

> 1. It is merely a conventional representation.

It's conventional... at least in aerospace literatures. However, for users who are not familiar to aerospace control, I'll add some references for them.

> 3\. No description of the unit quaternion.

There is no need to explain what unit quaternion is for rotational representation.

**Comment by JinraeKim** [comment]
Well, if you think so, I don't wanna rush you.

**Comment by seong-hun** [comment]
If you are confused, please clarify how the explanation can be misunderstood and please suggest any additional description that satisfy you through a PR.

**Comment by JinraeKim** [comment]
> If you are confused, please clarify how the explanation can be misunderstood and please suggest any additional description that satisfy you through a PR.

My pleasure :)

**Comment by seong-hun** [comment]
#168
Now I understand why you said current docstring is insufficient... Thanks a lot.
