### ISSUE TITLE
Incorrect parameters for quadcopter model

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-nrf/fym#171]
See [this line](https://github.com/fdcl-nrf/fym/blob/c40448974dd4480ea4135aebb707542145f85c70/fym/models/quadrotor.py#L24) and compare with [the original paper](https://github.com/fdcl-ftc/fault-tolerant-control/issues/75#issuecomment-855509722).

**Comment by seong-hun** [comment]
Thanks a lot!
