### ISSUE TITLE
`external` 인자를 좀 더 깔끔하게 처리할 수 없을까요?

### ISSUE THREAD

**Issue by seong-hun** [fdcl-nrf/fym#66]
현재 `external` 은 `env` 의 모든 `state` 정보를 가지고 있는 `dict` 입니다. 이것을 현재는 굳이 `deriv` 등에서 인자로 따로 받고 있는데요, `self.parent.states` 와 같이 접근 가능한 값을 또 인자로 받는 방식이 직관적이지 않습니다.

제어 학계에서 직관적으로 사용되는 `f(t, x, u)` 형식에 맞게 고칠 필요가 있는 것 같습니다.

**Comment by JinraeKim** [comment]
제어 학계에서 직관적... 이 문장이 무슨 뜻이죠?

**Comment by seong-hun** [comment]
#100 에서 해당 이슈를 해결하였으므로 닫겠습니다.
