### ISSUE TITLE
`test` 폴더 안에 스크립트를 다 넣어 놓기

### ISSUE THREAD

**Issue by seong-hun** [fdcl-nrf/fym#68]
루트 디렉터리에 들어 있는 스크립트를 `test` 디렉터리에 다 넣어서 깔끔하게 유지하면 좋겠습니다.

**Comment by JinraeKim** [comment]
충돌을 피하기 위해 이번 마일스톤 다 정리되면 옮깁시다

**Comment by seong-hun** [comment]
@JinraeKim Good!
